services:
  - type: web
    name: shreya-narsimha-wedding
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20.18.0"
